name: Survey API CI - Staging

on:
  push:
    branches:
      - stage    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy app
        run: |
          echo $ssh_key > ~/STAGING_SERVER_SSH_KEY
          chmod 400 ~/STAGING_SERVER_SSH_KEY
          cat ~/STAGING_SERVER_SSH_KEY
          ls -la ~/
        shell: bash
    env:
      ssh_key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
    environment: 
      name: staging
      url: https://stage.potentialisation.com
