name: Survey API CI - Staging

on:
  push:
    branches:
      - stage    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh and deploy app
        shell: bash
        env:
          TEST_SECRET: "${{ secrets.TEST_SECRET }}"
        run: |
          echo ">> $TEST_SECRET"
          echo ">> $GITHUB_CONTEXT"
          echo ${TEST_SECRET} > ~/FILE.TXT
          cat ~/FILE.TXT
      - run: echo '${{ toJSON(github) }}'
          
