name: Survey API CI - Staging

on:
  push:
    branches:
      - stage    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: ssh and deploy app
        shell: bash
        env:
          TEST_SECRET: ${{ secrets.STAGING_SERVER_SSH_KEY }}
        run: |
          echo "$TEST_SECRET" > github_id_rsa
          sudo chmod 600 github_id_rsa
          ssh -vi github_id_rsa -oStrictHostKeyChecking=no github@34.122.247.158 "touch HI_FROM_GIT"
          
